server:
  port: ${sp.setting}

#  tomcat:
#    uri-encoding: UTF-8
#  servlet:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true
#spring:
#  application:
#    name: ${sn.setting}
#spring:
#  profiles:
#    active: share

#  application:
#    name: setting-service
#  redis:
#    database: 0
#    host: online.redis.com
#    port: 6379
#    password: abc123
#    pool:
#      max-active: 300
#      max-wait: 10000
#      max-idle: 100
#      min-idle: 0
#      timeout: 0
#
#  mysql:
#    datasource:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://online.mysql.com:3306/zosc_tt?useSSL=false&serverTimezone=GMT%2B8&CharsetEncoding=UTF-8
#      username: root
#      password: abc123

  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: ${sn.setting}

seata:
  tx-service-group: tx-business
  enabled: true
  service:
    #seata服务地址
    grouplist:
      default: ${seata.default}
    #虚拟组和分组映射，key的名字与tx-service-group一致
    vgroup-mapping:
      tx-business: default
    #开启全局事务
    disable-global-transaction: false

